export const HEIGHT = 48;
export const FONT_SIZE = 17;
export const BORDER_RADIUS = 26;
export const CORNERS = 999;
export const FONT_SIZE_TITLE =26
export const FONT_SIZE_SEMI_TITLE =24
export const FONT_SIZE_MEDUIME =20
export const FONT_SIZE_NORMAL =18
export const FONT_SIZE_SMALL =14
export const FONT_SIZE_EXTRA_SMALL =10