export const HEIGHT = 48;
export const FONT_SIZE = 17;
export const BORDER_RADIUS = 26;
export const CORNERS = 999;
export const FONT_SIZE_TITLE =26
export const FONT_SIZE_SEMI_TITLE =24
export const FONT_SIZE_MEDUIME =20
export const FONT_SIZE_NORMAL =18
export const FONT_SIZE_SMALL =14
export const FONT_SIZE_EXTRA_SMALL =10
export const FONT_SIZE_XSMALL = 8;        // Extra extra small
export const FONT_SIZE_CARD_TITLE = 13;   // Card specific title
export const FONT_SIZE_RATING = 10;       // Rating text
export const FONT_SIZE_PRICE = 14;        // Price text
export const FONT_SIZE_QUANTITY_BUTTON = 14; // Quantity button
export const FONT_SIZE_QUANTITY = 12;     // Quantity number